name: C/C++ CI

on: [pull_request]

jobs:
  TiCS:
    name: TiCS
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make all
      - name: TICS Action Run
        uses: tiobe/tics-github-action@tiobe-patch-PR31241
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TICSAUTHTOKEN: ${{secrets.TICSAUTHTOKEN}}
        with:
          projectName: 'c-demo'
          installTics: true
          ticsConfiguration: 'https://testlab.tiobe.com/tiobeweb/testlab/api/cfg?name=testlab'
          tmpDir: '/tmp/c-demo'
          calc: 'CW,CS'
          showAnnotations: true